data = [
    ("Tu hoti toh", "Bharat Chauhan", ""),
    ("Village Damsel", "Indian ocean", "Indian ocean"),
    ("Out of the Blues", "Indian ocean", "Indian ocean"),
    ("Melancholic Ecstasy", "Indian ocean", "Indian ocean"),
    ("Going To ITO", "Indian ocean", "Indian ocean"),
    ("Torrent", "Indian ocean", "Indian ocean"),
    ("No Comebacks", "Indian ocean", "Indian ocean"),
    ("Brisk Lonely Walk", "Indian ocean", "Indian ocean"),
    ("Chori Chori", "junoon", "Junoon"),
    ("Neend Athi Nahin", "junoon", "Junoon"),
    ("Jiyain (feat. Fifi Haroon)", "junoon", "Junoon"),
    ("Jogia (feat. Fifi Haroon)", "junoon", "Junoon"),
    ("Heer (Instrumental)", "junoon", "Junoon"),
    ("Khwab", "junoon", "Junoon"),
    ("Meré Pass Aaja", "junoon", "Junoon"),
    ("Rangon Main Khoya", "junoon", "Junoon"),
    ("You Never Give Me Your Love", "junoon", "Junoon"),
    ("Game of Chance", "junoon", "Junoon"),
    ("Sunn", "junoon", "Junoon"),
    ("Downtown Princes", "junoon", "Junoon"),
    ("Heeray", "junoon", "Talaash"),
    ("Pehli Lagan", "junoon", "Talaash"),
    ("Woh", "junoon", "Talaash"),
    ("Ghaflat", "junoon", "Talaash"),
    ("Lady Magic", "junoon", "Talaash"),
    ("Aap Aur Hum (Instrumental)", "junoon", "Talaash"),
    ("Talaash", "junoon", "Talaash"),
    ("If You Want", "junoon", "Talaash"),
    ("Bheegi Yaadein", "junoon", "Talaash"),
    ("Our Land", "junoon", "Talaash"),
    ("Barzakh (Instrumental)", "junoon", "Talaash"),
    ("Himalayan Song (Instrumental)", "junoon", "Talaash"),
]
